GET http://localhost:8080/rest_start/api/person/4
###
POST http://localhost:8080/rest_start/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "Jon", "lastName": "Hammer", "phone": "12345678"}
###
PUT http://localhost:8080/rest_start/api/person/6
###
DELETE http://localhost:8080/rest_start/api/person/12

